# Generated by Django 6.0.4 on 2026-04-18 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_interesados', to='catalogo.productos')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='mis_favoritos', to='catalogo.users')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'db_table': 'favoritos',
                'unique_together': {('user', 'producto')},
            },
        ),
    ]
